# Generated by Django 2.2.5 on 2019-09-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('goal_name', models.CharField(max_length=255)),
                ('goal_percentage', models.IntegerField()),
                ('goal_period', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.IntegerField(primary_key=True, serialize=False)),
                ('story_name', models.CharField(max_length=255)),
                ('story_type', models.CharField(max_length=255)),
                ('story_level', models.CharField(max_length=255)),
                ('story_description', models.CharField(max_length=255)),
                ('story_comment', models.TextField()),
                ('story_action', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('user_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
    ]
