# Generated by Django 2.2.5 on 2019-09-15 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeera_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('goal_name', models.CharField(max_length=255)),
                ('goal_period', models.CharField(max_length=255)),
                ('goal_progress', models.IntegerField(default=0)),
                ('goal_weightage', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_git', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
        migrations.AddField(
            model_name='story',
            name='story_weightage',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_action',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_story',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jeera_app.Story'),
        ),
        migrations.AddField(
            model_name='story',
            name='story_project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jeera_app.Project'),
        ),
    ]
