# Generated by Django 2.2.6 on 2019-10-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeera_app', '0002_auto_20190915_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
