# Generated by Django 2.2.6 on 2019-10-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeera_app', '0003_goal_goal_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goal_progress',
        ),
    ]
