# Generated by Django 2.2.6 on 2019-11-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeera_app', '0005_goal_goal_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_progress',
            field=models.IntegerField(default=0),
        ),
    ]
